#!/usr/bin/perl -w

# Generate usys.S, the stubs for syscalls.
# 根據裡面列的函數，生成 user/usys.S 組語碼，這些才是真正發動 syscall 的 stub
# stub: user space 呼叫 kernel function 的「轉接 stub」，幫你把函數 call 轉成底層的 ecall

print "# generated by usys.pl - do not edit\n";

print "#include \"kernel/syscall.h\"\n";

sub entry {
    my $name = shift;
    print ".global $name\n";
    print "${name}:\n";
    print " li a7, SYS_${name}\n";
    print " ecall\n";
    print " ret\n";
}
	
entry("fork");
entry("exit");
entry("wait");
entry("pipe");
entry("read");
entry("write");
entry("close");
entry("kill");
entry("exec");
entry("open");
entry("mknod");
entry("unlink");
entry("fstat");
entry("link");
entry("mkdir");
entry("chdir");
entry("dup");
entry("getpid");
entry("sbrk");
entry("sleep");
entry("uptime");
entry("trace");
